title: Dev Log & Lab
email: aidasofialily@gmail.com
description: >-
  A collection of technical deep-dives and creative coding experiments.
baseurl: "" 
url: "https://aidasofialily-cmd.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
